language: php

sudo: false

php:
  - '7.0'

matrix:
    fast_finish: true

cache:
    directories:
      - $HOME/.composer/cache/files

install:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
